- name: Run hello-world.sh
  hosts: all
  tasks:
    - name: copy script
      copy:
        src: hello-world.sh
        dest: /tmp/hello-world.sh
        mode: '0777'
    - name: Hello Script
      script: /tmp/hello-world.sh